name: "Deploy for AWS in production enviroment"
on:
  push:
    branches:
      - main
    
env:
  TF_VAR_ssh_key: ${{ secrets.SSH_KEY_EC2_AWS }}

jobs:

  Trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write 

    steps:
      - name: "Checkout do código"
        uses: actions/checkout@v4

      - name: Run Trivy IaC Scanner
        uses: aquasecurity/trivy-action@v0.36.0 # Match latest verified action tag
        env:
          TRIVY_SKIP_VERSION_CHECK: "true"
          TRIVY_IGNOREFILE: ".trivyignore"
          
        with:
          scan-type: 'config'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'
          limit-severities-for-sarif: true 
          exit-code: '1' # Fails the pipeline if issues are discovered
          format: 'sarif'
          output: 'trivy-results.sarif'
    
      - name: Show trivy-results.sarif
        run: cat trivy-results.sarif

      - name: Upload Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v4
        if: always() # Ensures logs upload even if vulnerabilities break the build
        with:
          sarif_file: 'trivy-results.sarif'

  Configuration:
    needs: Trivy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout do código"
        uses: actions/checkout@v4

      - name: "Configure AWS credentials"
        uses:  aws-actions/Configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN }}
          aws-region: us-west-2

      - name: "Running applies"
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: "1.12"

      - name: "Terraform Init"
        run: terraform init

      - name: "terraform checkout"
        run: terraform fmt -check -recursive

      - name: "Terraform Validate"
        run: terraform validate

      - name: "Terraform Plan"
        run: terraform plan -out=tfplan

      - name: "Terraform apply"
        run: terraform apply tfplan