name: "Deploy for AWS in dev enviroment"
on:
  push:
    branches:
      - dev

env:
  TF_VAR_ssh_key: ${{ secrets.SSH_KEY_EC2_AWS }}

jobs:
  Configuration:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout do código"
        uses: actions/checkout@v4

      - name: "Configure AWS credentials"
        uses:  aws-actions/Configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN }}
          aws-region: us-west-2

      - name: "Running applies"
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: "1.12"

      - name: "terraform init"
        run: terraform init

      - name: "terraform checkout"
        run: terraform fmt -check -recursive

      - name: "terraform plan"
        run: terraform plan